/* ========================================
   AI VISUALS DATA
   MidJourney-generated images & videos for the 'AI Visuals' category.
   thumb = small lazy-loaded grid/strip image; src = full image or mp4.
   ======================================== */

const AI_VISUALS = [
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/001.jpg', src: 'assets/projects/ai-visuals/full/001.jpg', label: 'Crane Maiden' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/002.jpg', src: 'assets/projects/ai-visuals/full/002.jpg', label: 'Blossom Smoke Drive' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/003.jpg', src: 'assets/projects/ai-visuals/video/003.mp4', label: 'Meadow Run' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/004.jpg', src: 'assets/projects/ai-visuals/full/004.jpg', label: 'Ferry Window Dusk' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/005.jpg', src: 'assets/projects/ai-visuals/video/005.mp4', label: 'Tea By The Strait' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/006.jpg', src: 'assets/projects/ai-visuals/video/006.mp4', label: 'Gilded Lion Veil' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/007.jpg', src: 'assets/projects/ai-visuals/video/007.mp4', label: 'Porcelain Dancers' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/008.jpg', src: 'assets/projects/ai-visuals/video/008.mp4', label: 'Cosmic Panther' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/009.jpg', src: 'assets/projects/ai-visuals/video/009.mp4', label: 'Glowing-Heart Fawn' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/010.jpg', src: 'assets/projects/ai-visuals/full/010.jpg', label: 'Crystal-Heart Doe' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/011.jpg', src: 'assets/projects/ai-visuals/full/011.jpg', label: 'Luminous Fawn' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/012.jpg', src: 'assets/projects/ai-visuals/video/012.mp4', label: 'Floating Bed Voyage' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/013.jpg', src: 'assets/projects/ai-visuals/video/013.mp4', label: 'Stormwater Stallion' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/014.jpg', src: 'assets/projects/ai-visuals/video/014.mp4', label: 'Cartographer Steed' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/015.jpg', src: 'assets/projects/ai-visuals/video/015.mp4', label: 'Map-Coat Horse' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/016.jpg', src: 'assets/projects/ai-visuals/full/016.jpg', label: 'Compass-Star Mare' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/017.jpg', src: 'assets/projects/ai-visuals/video/017.mp4', label: 'Spring Window Girl' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/018.jpg', src: 'assets/projects/ai-visuals/video/018.mp4', label: 'Jar Of Stars' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/019.jpg', src: 'assets/projects/ai-visuals/full/019.jpg', label: 'Caged Heart' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/020.jpg', src: 'assets/projects/ai-visuals/full/020.jpg', label: 'Linen Rabbit' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/021.jpg', src: 'assets/projects/ai-visuals/video/021.mp4', label: 'Lantern Antlers' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/022.jpg', src: 'assets/projects/ai-visuals/video/022.mp4', label: 'Tomato Garden' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/023.jpg', src: 'assets/projects/ai-visuals/full/023.jpg', label: 'Sunflower Path' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/024.jpg', src: 'assets/projects/ai-visuals/full/024.jpg', label: 'Cloud Tram' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/025.jpg', src: 'assets/projects/ai-visuals/full/025.jpg', label: 'Crossing The Flats' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/026.jpg', src: 'assets/projects/ai-visuals/full/026.jpg', label: 'Mountain Blossom Ride' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/027.jpg', src: 'assets/projects/ai-visuals/full/027.jpg', label: 'Cherry Blossom Lane' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/028.jpg', src: 'assets/projects/ai-visuals/full/028.jpg', label: 'Moonlit Daydream' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/029.jpg', src: 'assets/projects/ai-visuals/full/029.jpg', label: 'White Fox Friend' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/030.jpg', src: 'assets/projects/ai-visuals/full/030.jpg', label: 'Red Coat Snow' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/031.jpg', src: 'assets/projects/ai-visuals/full/031.jpg', label: 'Festival Goldfish' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/032.jpg', src: 'assets/projects/ai-visuals/full/032.jpg', label: 'Winter Window Tea' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/033.jpg', src: 'assets/projects/ai-visuals/full/033.jpg', label: 'Whale Among Clouds' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/034.jpg', src: 'assets/projects/ai-visuals/full/034.jpg', label: 'Shepherd In Clouds' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/035.jpg', src: 'assets/projects/ai-visuals/video/035.mp4', label: 'Starlit Rooftop Night' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/036.jpg', src: 'assets/projects/ai-visuals/full/036.jpg', label: 'Snowy Forest Path' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/037.jpg', src: 'assets/projects/ai-visuals/full/037.jpg', label: 'Joyful Biplane Flight' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/038.jpg', src: 'assets/projects/ai-visuals/full/038.jpg', label: 'Clouds And Aircraft' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/039.jpg', src: 'assets/projects/ai-visuals/full/039.jpg', label: 'Empty Station Departure' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/040.jpg', src: 'assets/projects/ai-visuals/video/040.mp4', label: 'Antennae Under Stars' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/041.jpg', src: 'assets/projects/ai-visuals/full/041.jpg', label: 'Mushroom House Doorstep' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/042.jpg', src: 'assets/projects/ai-visuals/full/042.jpg', label: 'Resting By Toadstool' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/043.jpg', src: 'assets/projects/ai-visuals/full/043.jpg', label: 'Blossom Bridge Spring' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/044.jpg', src: 'assets/projects/ai-visuals/full/044.jpg', label: 'Grandmother And Kitten' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/045.jpg', src: 'assets/projects/ai-visuals/full/045.jpg', label: 'Soot Sprites Hideout' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/046.jpg', src: 'assets/projects/ai-visuals/full/046.jpg', label: 'Library Reading Nook' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/047.jpg', src: 'assets/projects/ai-visuals/full/047.jpg', label: 'Rainy Stone Bridge' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/048.jpg', src: 'assets/projects/ai-visuals/full/048.jpg', label: 'Telescope And Stars' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/049.jpg', src: 'assets/projects/ai-visuals/full/049.jpg', label: 'Stargazing Through Telescope' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/050.jpg', src: 'assets/projects/ai-visuals/full/050.jpg', label: 'Spirit Festival Night' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/051.jpg', src: 'assets/projects/ai-visuals/full/051.jpg', label: 'Lantern Spirit Market' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/052.jpg', src: 'assets/projects/ai-visuals/full/052.jpg', label: 'Riverside Frog Companion' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/053.jpg', src: 'assets/projects/ai-visuals/full/053.jpg', label: 'Ramen Stall Alley' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/054.jpg', src: 'assets/projects/ai-visuals/full/054.jpg', label: 'Rainy Storefront Umbrella' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/055.jpg', src: 'assets/projects/ai-visuals/full/055.jpg', label: 'Snowfall Lantern Glow' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/056.jpg', src: 'assets/projects/ai-visuals/full/056.jpg', label: 'Maple Tea Porch' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/057.jpg', src: 'assets/projects/ai-visuals/full/057.jpg', label: 'Crimson Leaves Cottage' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/058.jpg', src: 'assets/projects/ai-visuals/full/058.jpg', label: 'Zen Garden Children' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/059.jpg', src: 'assets/projects/ai-visuals/full/059.jpg', label: 'Catbus At Dusk' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/060.jpg', src: 'assets/projects/ai-visuals/full/060.jpg', label: 'Submarine Porthole View' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/061.jpg', src: 'assets/projects/ai-visuals/full/061.jpg', label: 'Moonlit Hilltop Town' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/062.jpg', src: 'assets/projects/ai-visuals/full/062.jpg', label: 'Thatched Cottage Path' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/063.jpg', src: 'assets/projects/ai-visuals/full/063.jpg', label: 'Rooftop Above Lights' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/064.jpg', src: 'assets/projects/ai-visuals/full/064.jpg', label: 'Fireflies Stone Shrine' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/065.jpg', src: 'assets/projects/ai-visuals/full/065.jpg', label: 'Meadow Joy' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/066.jpg', src: 'assets/projects/ai-visuals/full/066.jpg', label: 'Fireflies Wood' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/067.jpg', src: 'assets/projects/ai-visuals/video/067.mp4', label: 'Stained-Glass Fox' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/068.jpg', src: 'assets/projects/ai-visuals/full/068.jpg', label: 'Glowing Glass Fox' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/069.jpg', src: 'assets/projects/ai-visuals/video/069.mp4', label: 'Alpine Train Window' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/070.jpg', src: 'assets/projects/ai-visuals/video/070.mp4', label: 'Night Kitchen' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/071.jpg', src: 'assets/projects/ai-visuals/video/071.mp4', label: 'Sunbeam Cat' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/072.jpg', src: 'assets/projects/ai-visuals/full/072.jpg', label: 'Crimson Foal' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/073.jpg', src: 'assets/projects/ai-visuals/full/073.jpg', label: 'Pale Watcher' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/074.jpg', src: 'assets/projects/ai-visuals/full/074.jpg', label: 'Corner Storefront' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/075.jpg', src: 'assets/projects/ai-visuals/full/075.jpg', label: 'Red Doorway Self' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/076.jpg', src: 'assets/projects/ai-visuals/video/076.mp4', label: 'Crimson Mirror' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/077.jpg', src: 'assets/projects/ai-visuals/full/077.jpg', label: 'Sky Of Fish' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/078.jpg', src: 'assets/projects/ai-visuals/video/078.mp4', label: 'Great Sky Carp' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/079.jpg', src: 'assets/projects/ai-visuals/video/079.mp4', label: 'Rainfall Shrine' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/080.jpg', src: 'assets/projects/ai-visuals/video/080.mp4', label: 'Candlelit Scholar' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/081.jpg', src: 'assets/projects/ai-visuals/video/081.mp4', label: 'Owl Library Scholar' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/082.jpg', src: 'assets/projects/ai-visuals/video/082.mp4', label: 'Train Window Daydream' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/083.jpg', src: 'assets/projects/ai-visuals/full/083.jpg', label: 'Art Nouveau Cat' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/084.jpg', src: 'assets/projects/ai-visuals/video/084.mp4', label: 'Bowl Of Joy' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/085.jpg', src: 'assets/projects/ai-visuals/full/085.jpg', label: 'Crimson Crane Geisha' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/086.jpg', src: 'assets/projects/ai-visuals/full/086.jpg', label: 'Freckled War Paint' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/087.jpg', src: 'assets/projects/ai-visuals/full/087.jpg', label: 'Lacquer Doll Bride' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/088.jpg', src: 'assets/projects/ai-visuals/video/088.mp4', label: 'Witch Descending' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/089.jpg', src: 'assets/projects/ai-visuals/full/089.jpg', label: 'The Fox Mask' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/090.jpg', src: 'assets/projects/ai-visuals/full/090.jpg', label: 'Wildflower Iris' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/091.jpg', src: 'assets/projects/ai-visuals/full/091.jpg', label: 'Gilded Bloom Gaze' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/092.jpg', src: 'assets/projects/ai-visuals/full/092.jpg', label: 'Daisy-Framed Eye' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/093.jpg', src: 'assets/projects/ai-visuals/full/093.jpg', label: 'Camellia Grandmother' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/094.jpg', src: 'assets/projects/ai-visuals/video/094.mp4', label: 'Flight Over Rooftops' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/095.jpg', src: 'assets/projects/ai-visuals/full/095.jpg', label: 'Blindfolded Devotion' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/096.jpg', src: 'assets/projects/ai-visuals/full/096.jpg', label: 'Bouquet Of Eyes' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/097.jpg', src: 'assets/projects/ai-visuals/video/097.mp4', label: 'Mushroom Reverie' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/098.jpg', src: 'assets/projects/ai-visuals/full/098.jpg', label: 'Tree Frog Gaze' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/099.jpg', src: 'assets/projects/ai-visuals/full/099.jpg', label: 'Cradled Chick' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/100.jpg', src: 'assets/projects/ai-visuals/full/100.jpg', label: 'Snail On Teacup' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/101.jpg', src: 'assets/projects/ai-visuals/full/101.jpg', label: 'Chick On Shoulder' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/102.jpg', src: 'assets/projects/ai-visuals/full/102.jpg', label: 'Carrot Kitchen' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/103.jpg', src: 'assets/projects/ai-visuals/full/103.jpg', label: 'Spreading The Toast' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/104.jpg', src: 'assets/projects/ai-visuals/video/104.mp4', label: 'Cucumber Slices' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/105.jpg', src: 'assets/projects/ai-visuals/video/105.mp4', label: 'Peaches And Berries' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/106.jpg', src: 'assets/projects/ai-visuals/video/106.mp4', label: 'Soaring Over Town' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/107.jpg', src: 'assets/projects/ai-visuals/full/107.jpg', label: 'Lace Veiled Porcelain' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/108.jpg', src: 'assets/projects/ai-visuals/video/108.mp4', label: 'Pearl Crowned Mask' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/109.jpg', src: 'assets/projects/ai-visuals/full/109.jpg', label: 'Crimson Petal Wave' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/110.jpg', src: 'assets/projects/ai-visuals/full/110.jpg', label: 'Golden Tide Rising' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/111.jpg', src: 'assets/projects/ai-visuals/video/111.mp4', label: 'Fresh From The Oven' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/112.jpg', src: 'assets/projects/ai-visuals/video/112.mp4', label: 'Frosting The Cake' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/113.jpg', src: 'assets/projects/ai-visuals/full/113.jpg', label: 'Handwritten Pages' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/114.jpg', src: 'assets/projects/ai-visuals/video/114.mp4', label: 'Cherry Blossom Ride' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/115.jpg', src: 'assets/projects/ai-visuals/full/115.jpg', label: 'Two Briefcases' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/116.jpg', src: 'assets/projects/ai-visuals/video/116.mp4', label: 'Girl And Ginger Cat' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/117.jpg', src: 'assets/projects/ai-visuals/video/117.mp4', label: 'Smiling Cat Steam' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/118.jpg', src: 'assets/projects/ai-visuals/video/118.mp4', label: 'Copper Still Kitchen' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/119.jpg', src: 'assets/projects/ai-visuals/video/119.mp4', label: 'Pouring The Kettle' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/120.jpg', src: 'assets/projects/ai-visuals/full/120.jpg', label: 'Chopping Carrots' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/121.jpg', src: 'assets/projects/ai-visuals/full/121.jpg', label: 'Cozy Bakery Kitchen' },
                { type: 'video', thumb: 'assets/projects/ai-visuals/thumbs/122.jpg', src: 'assets/projects/ai-visuals/video/122.mp4', label: 'Stirring The Pot' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/123.jpg', src: 'assets/projects/ai-visuals/full/123.jpg', label: 'Little Cook Stirring' },
                { type: 'image', thumb: 'assets/projects/ai-visuals/thumbs/124.jpg', src: 'assets/projects/ai-visuals/full/124.jpg', label: 'Crimson Gown' },
];

if (typeof window !== 'undefined') { window.AI_VISUALS = AI_VISUALS; }
